services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=kanban'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=kanban_db_user'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: